from typing import Union

class PyBIP158:
    def __init__(self, content: Union[list[Union[bytes, bytearray]], bytes, bytearray]) -> None: ...
    def GetEncoded(self) -> bytes: ...
    def Match(self, query: Union[bytes, bytearray]) -> bool: ...
    def MatchAny(self, queries: list[Union[bytes, bytearray]]) -> bool: ...
