# adapted from https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish Python distributions to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies on ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install libboost-all-dev
    - name: Install dependencies on Mac
      if: startsWith(matrix.os, 'mac')
      run: |
        brew install boost
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pep517
      run: >-
        python -m
        pip install
        pep517
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        pep517.build
        --binary
        --out-dir dist/
        .
    - name: Upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels-${{ matrix.os }}
        path: dist
    - name: Publish distribution to Test PyPI
      if: 1
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
